services:
  # MAIN BOT
  - type: web
    name: femboy-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python areufemboy.py
    envVars:
      BOT_TOKEN:
        fromDatabase:
          name: BOT_TOKEN
          property: value

  # KEEP-ALIVE PINGER
  - type: web
    name: femboy-pinger
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
    healthCheckPath: /
